---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.10b0 # This should be kept in sync with the version in requirements-dev.in
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.0.0 # This should be kept in sync with the version in requirements-dev.in
    hooks:
      - id: pydocstyle
        args:
        - --ignore=D100,D103,D212
