name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Use pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            pip-
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -r requirements-dev.txt
          pip install hail gnomad
      - name: Check formatting
        run: black --check .
      - name: Check docstrings
        run: pydocstyle
      - name: Run Pylint
        run: python -m pylint gnomad_mitochondria
